version: '3.8'

services:
  app:
    build: .
    container_name: latex-app
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data:/app/data  # том для хранения базы данных SQLite
    networks:
      - latex-network

networks:
  latex-network:
    driver: bridge
